server:
  port: 8080
  # GateWay Logging 日志
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
spring:
  application:
    name: ampieta-game-cloud-gateway
  #gateway的配置
  cloud:
    gateway:
      #路由规则
      routes: 
        - id: home_route
          uri: http://127.0.0.1:8000 #需要转发到地址
          #断言规则 用于路由规则的匹配
          predicates:
            - Path=/api/**
            # http://127.0.0.1:8080/api/version