#路径
server:
  address: 127.0.0.1
  port: 8020
  servlet:
    context-path: /

# 自定义属性
web:
  path: /usr/local/static

spring:
  application:
    name: ampieat-server

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
